export const images = [
  "image1_lr.png",
  "image2_lr.png",
  "image3_lr.png",
  "image4_lr.png",
  "image5_lr.png",
  "image6_lr.png",
  "image7_lr.png",
  "image8_lr.png",
  "image9_lr.png",
  "image10_lr.png",
  "image11_lr.png",
  "image12_lr.png",
];

export const goals = [
  "Rages at game",
  "Let's read chat",
  "Dad sneeze",
  "Goes to toilet for 2 years",
  "Crackhead story",
  "Out of pocket comment",
  "Says the word owl",
  "Minecraft villager noise",
  "Gets sidetracked",
  "Does something stupid in game",
  "Singles out member of chat",
  "Calls himself old",
  "Verkel",
  "Shrimp farm",
  "Tekilia",
  "Obscure reference to some random meme",
  "Lighskin stare/rizz",
  "Talks about isha",
  "Terrible advice",
  "Laughing at his own joke",
  "Dated slang",
  "Goblin laugh",
  "Racially charged comment",
  "Politics",
  "Pretend crying",
  "Capitalism",
  "Talks about ancient history",
  "Terrible pick up line",
  "Brings up rich people",
  "Gay",
  "30+ minute rant",
  "Animal facts",
  "Deliberate cringe",
  '"Do you think/what if?"',
  "Tea propaganda",
];
